# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from . import my_pb2 as my__pb2
# import my_pb2 as my__pb2


class FileTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Case4 = channel.stream_stream(
                '/grpc_stream_x2.FileTransferService/Case4',
                request_serializer=my__pb2.FileRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )
        self.Case5 = channel.unary_unary(
                '/grpc_stream_x2.FileTransferService/Case5',
                request_serializer=my__pb2.BatchRequest.SerializeToString,
                response_deserializer=my__pb2.FileResponse.FromString,
                )


class FileTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Case4(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Case5(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Case4': grpc.stream_stream_rpc_method_handler(
                    servicer.Case4,
                    request_deserializer=my__pb2.FileRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
            'Case5': grpc.unary_unary_rpc_method_handler(
                    servicer.Case5,
                    request_deserializer=my__pb2.BatchRequest.FromString,
                    response_serializer=my__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_stream_x2.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Case4(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/grpc_stream_x2.FileTransferService/Case4',
            my__pb2.FileRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Case5(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_stream_x2.FileTransferService/Case5',
            my__pb2.BatchRequest.SerializeToString,
            my__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
